site_name: Longvinter Server Docs
site_url: https://docs-server.longvinter.com
site_description: Longvinter Server Documentation for Administrators
site_author: Uuvana Studios

repo_url: https://github.com/Uuvana-Studios/Longvinter-server-documentation
edit_uri: ""

theme:
    name: mkdocs
    locale: en
    highlightjs: true
    
copyright: Copyright &copy; 2021 <a href="https://github.com/Uuvana-Studios">Uuvana Studios</a>.
