site_name: Longvinter Server Docs
site_url: https://docs-server.longvinter.com
site_description: Longvinter Server Documentation for Server Administrators
site_author: Uuvana Studios

repo_url: https://github.com/Uuvana-Studios/Longvinter-server-documentation
repo_name: Improve this page
edit_uri: ""

nav:
    - Home: 'index.md'
    - 'Linux Guide':
        - 'Vanilla Setup': 'linux/setup-vanilla.md'
        - 'Docker Setup': 'linux/setup-docker.md'
    - Windows Guide:
        - 'Vanilla Setup': 'windows/setup-vanilla.md'
        - 'Docker Setup': 'windows/setup-docker.md'

theme:
  name: material
  custom_dir: overrides
  locale: en

extra_css:
  - css/hint.min.css

plugins:
  - search
  - git-authors
  - tooltips
  - enumerate-headings:
      exclude:
        - index.md
        - linux/index.md
        - windows/index.md
  - i18n:
      default_language: en
      languages:
        en:
          name: English
          build: true
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
          remove_comments: true
      css_files:
          - css/hint.min.css
    
copyright: Copyright &copy; 2021 <a href="https://github.com/Uuvana-Studios">Uuvana Studios</a>.
