site_name: Longvinter Server Docs
site_url: https://docs-server.longvinter.com
site_description: Longvinter Server Documentation for Server Administrators
site_author: Uuvana Studios

repo_url: https://github.com/Uuvana-Studios/Longvinter-server-documentation
repo_name: Improve this page
edit_uri: tree/master/docs

nav:
    - Home: 'index.md'
    - 'Linux Guide':
        - 'Vanilla Setup': 'linux/setup-vanilla.md'
        - 'Docker Setup': 'linux/setup-docker.md'
    - Windows Guide:
        - 'Vanilla Setup': 'windows/setup-vanilla.md'
        - 'Docker Setup': 'windows/setup-docker.md'

theme:
  name: material
  custom_dir: docs/overrides

  locale: en

  font:
    text: Roboto
    code: Roboto Mono

  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  features:
    - tabs
    - instant
    - content.code.annotate
    # - content.tabs.link
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

# Customization
extra:
  homepage: https://docs-server.longvinter.com
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Uuvana-Studios
    - icon: fontawesome/brands/discord
      link: https://discord.gg/longvinter
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/longvinter
    - icon: fontawesome/brands/reddit
      link: https://www.reddit.com/r/Longvinter
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCFI5P49Zg2bBuobBLVAiDPw
    - icon: fontawesome/brands/tiktok
      link: https://www.tiktok.com/@longvinter

extra_css:
  - css/hint.min.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/vega@5
  - https://cdn.jsdelivr.net/npm/vega-lite@5
  - https://cdn.jsdelivr.net/npm/vega-embed@6

markdown_extensions:
  - abbr
  - footnotes
  - meta
  - tables
  - attr_list
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: vegalite
          class: vegalite
          format: !!python/name:mkdocs_charts_plugin.fences.fence_vegalite

plugins:
  - tooltips
  - charts

  - redirects:
      redirect_maps:
        'linux/index.md': 'linux/setup-vanilla.md'
        'windows/index.md': 'windows/setup-vanilla.md'

  - search:
      prebuild_index: true

  - enumerate-headings:
      exclude:
        - index.md
        - linux/index.md
        - windows/index.md

 # - i18n:
 #     default_language: en
 #     languages:
 #       en:
 #         name: English
 #         build: true

  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
          remove_comments: true
      css_files:
          - css/hint.min.css
      
  - git-revision-date-localized:
      type: timeago
      timezone: Europe/Helsinki
      locale: en
      fallback_to_build_date: false
      enable_creation_date: true

  - print-site:
      add_to_navigation: false
      add_full_urls: false
      add_table_of_contents: true
      toc_title: "Table of Contents"
      toc_depth: 2
      enumerate_headings: true
      enumerate_figures: true
      add_cover_page: true
    
copyright: Copyright &copy; 2021 <a href="https://github.com/Uuvana-Studios">Uuvana Studios</a>.
